import React from 'react';
import nextId from 'react-id-generator';

const products = [
	{
		_id: nextId('product-'),
		name: 'Furla Villa',
		images: [
			'/img/bags/W_Furla/1.jpg',
			'/img/bags/W_Furla/2.jpg',
			'/img/bags/W_Furla/3.jpg',
			'/img/bags/W_Furla/4.jpg',
			'/img/bags/W_Furla/5.jpg',
			'/img/bags/W_Furla/6.jpg',
			'/img/bags/W_Furla/7.jpg',
		],
		colors: ['#060D5C', '#A9DBD0', '#F2E2AE', '#26201D'],
		description:
			'Furla Villa выполнена из тисненной кожи теленка Milos. Благодаря удобному регулируемому съемному кожаному ремню аксессуар можно носить на плече или через плечо. Сумка, идеально подходящая для аккуратного хранения мелких предметов и личных вещей, имеет металлическую застежку с квадратным кольцом и замком с гравировкой Furla спереди.',
		brand: 'Furla',
		category: 'Bags',
		price: 36000,
		countInStock: 5,
		rating: 4.5,
		numReviews: 4,
		discount: true,
	},
	{
		_id: nextId('product-'),
		name: 'Furla 1925',
		images: [
			'/img/bags/W_FurlaMerin/1.jpg',
			'/img/bags/W_FurlaMerin/2.jpg',
			'/img/bags/W_FurlaMerin/3.jpg',
			'/img/bags/W_FurlaMerin/4.jpg',
			'/img/bags/W_FurlaMerin/5.jpg',
		],
		colors: ['#F5EFBC', '#E89B35', '#330C32', '#35E855'],
		description:
			'Мини-сумка кросс-боди Furla 1927 Soft выполнена из гладкой телячьей кожи Maya. Съемный текстильный ремень украшен легендарным логотипом Furla. В открытом кармане сзади удобно хранить самые необходимые вещи.',
		brand: 'Furla',
		category: 'Bags',
		price: 29000,
		countInStock: 7,
		rating: 4.3,
		numReviews: 15,
		discount: false,
	},
	{
		_id: nextId('product-'),
		name: 'LE 1440 GOLDY',
		images: [
			'/img/bags/W_LE1440GOLDY/1.webp',
			'/img/bags/W_LE1440GOLDY/2.webp',
			'/img/bags/W_LE1440GOLDY/3.webp',
			'/img/bags/W_LE1440GOLDY/4.webp',
		],
		colors: ['#F5DF78', '#EB9D1E', '#D2F4CA', '#332D0C'],
		description:
			'Женская сумка IKKS - модель LE 1440 M GOLDY. Эту сумку-шоппер среднего размера можно носить в руках или на плече, она украшена вставкой из стеганой кожи с зигзагообразным рисунком спереди и металлическими деталями цвета состаренного золота.',
		brand: 'LaRedoute',
		category: 'Bags',
		price: 32000,
		countInStock: 8,
		rating: 4.5,
		numReviews: 4,
		discount: false,
	},
	{
		_id: nextId('product-'),
		name: 'LaRedoute MACY',
		images: [
			'/img/bags/W_MACY/1.webp',
			'/img/bags/W_MACY/2.webp',
			'/img/bags/W_MACY/3.webp',
			'/img/bags/W_MACY/4.webp',
		],
		colors: ['#2E1D1A', '#485243', '#7D553C', '#6C7A5E'],
		description:
			'Женская сумка с ручками NAT & NIN - модель MACY. Кожаная сумка на молнии в форме портфеля с металлическими деталями золотистого цвета. Съемный плечевой ремень.',
		brand: 'LaRedoute',
		category: 'Bags',
		price: 30000,
		countInStock: 9,
		rating: 4,
		numReviews: 20,
		discount: true,
	},
	{
		_id: nextId('product-'),
		name: 'LaRedoute THE ARTIST',
		images: [
			'/img/bags/W_THEARTIST/1.webp',
			'/img/bags/W_THEARTIST/2.webp',
			'/img/bags/W_THEARTIST/3.webp',
			'/img/bags/W_THEARTIST/4.webp',
			'/img/bags/W_THEARTIST/5.webp',
		],
		colors: ['#33312D', '#243F40', '#9F71A3', '#8CA17D'],
		description:
			'Сумка женская IKKS -модель THE ARTIST. Сумка кожаная с 2-мя вариантами переноски: в руках и на плече. Большой размер с отделениями в городском стиле.',
		brand: 'LaRedoute',
		category: 'Bags',
		price: 28000,
		countInStock: 11,
		rating: 4.8,
		numReviews: 3,
		discount: true,
	},
	{
		_id: nextId('product-'),
		name: 'Titan Barbara 389704',
		images: [
			'/img/cosmetic_bags/Barbara389704/1.jpg',
			'/img/cosmetic_bags/Barbara389704/2.jpg',
			'/img/cosmetic_bags/Barbara389704/3.jpg',
		],
		colors: ['#803C19', '#3D311D', '#D9C675', '#6BA64B'],
		description: 'Косметичка Titan 389704 Barbara Velvet на молнии.',
		brand: 'Titan',
		category: 'CosmeticBags',
		price: 4000,
		countInStock: 20,
		rating: 3.8,
		numReviews: 5,
		discount: false,
	},
	{
		_id: nextId('product-'),
		name: 'Kipling KI2910Y92',
		images: [
			'/img/cosmetic_bags/Barbara389704/1.jpg',
			'/img/cosmetic_bags/Barbara389704/2.jpg',
			'/img/cosmetic_bags/Barbara389704/3.jpg',
			'/img/cosmetic_bags/Barbara389704/4.jpg',
			'/img/cosmetic_bags/Barbara389704/5.jpg',
		],
		colors: ['#8AD5DB', '#244032', '#5E7BA6', '#C9DB9B'],
		description:
			'Модель из прочного влагонепроницаемого полиэстера в оттенках «морской волны» и дополнена фирменным лейблом Kipling в единой цветовой гамме и узнаваемым хромированным брелоком в виде обезьянки, который стильно вписывается в общую концепцию дизайна. Не обошлось и без D-образного кольца для персонализации изделия дополнительными уникальными аксессуарами!',
		brand: 'Kipling',
		category: 'CosmeticBags',
		price: 7500,
		countInStock: 9,
		rating: 4.8,
		numReviews: 15,
		discount: false,
	},
	{
		_id: nextId('product-'),
		name: 'Titan 382704-04',
		images: [
			'/img/cosmetic_bags/Titan382704-04/1.jpg',
			'/img/cosmetic_bags/Titan382704-04/2.jpg',
			'/img/cosmetic_bags/Titan382704-04/3.jpg',
			'/img/cosmetic_bags/Titan382704-04/4.jpg',
		],
		colors: ['#BCD9C2', '#84A39C', '#373D31', '#807D44'],
		description:
			'Косметичка Titan 382704-04 Nonstop Cosmetic Bag на молнии, с внутренним карманом и возможностью крепления на руку чемодана',
		brand: 'Titan',
		category: 'CosmeticBags',
		price: 5500,
		countInStock: 10,
		rating: 4.2,
		numReviews: 7,
		discount: true,
	},
	{
		_id: nextId('product-'),
		name: 'Arya Suwi',
		images: [
			'/img/for_home/Cover_AryaSuwi/1.jpg',
			'/img/for_home/Cover_AryaSuwi/2.jpg',
			'/img/for_home/Cover_AryaSuwi/3.jpg',
			'/img/for_home/Cover_AryaSuwi/4.jpg',
		],
		colors: ['#7D492F', '#3B3326', '#D6CB9B', '#9DA16A'],
		description:
			'Покрывало Arya Suwi выполнено из высококачественного полиэстера, который на вид и ощупь не отличается от хлопка.  При этом полиэстер - такой вид ткани, который состоит из полиэфирных волокон. Благодаря этому ткани из полиэстера легкие, прочные и износостойкие.',
		brand: 'Suwi',
		category: 'ForHome',
		price: 9500,
		countInStock: 25,
		rating: 3.5,
		numReviews: 2,
		discount: false,
	},
	{
		_id: nextId('product-'),
		name: 'Покрывало из стираного льна, Elina',
		images: [
			'/img/for_home/Cover_Elina/1.webp',
			'/img/for_home/Cover_Elina/2.webp',
			'/img/for_home/Cover_Elina/3.webp',
		],
		colors: ['#383332', '#D3CECA', '#9E998E', '#E6D75E'],
		description:
			'Натуральный материал, уникальное сочетание аутентичности, комфорта и элегантности, лен является терморегулирующим материалом: прохладный летом и комфортный зимой… Выращенный в Европе, лен является легким в уходе и имеет слегка жатый эффект, поэтому гладка не требуется. Стираный для большей мягкости и современности, со временем он становится мягче и красивее.',
		brand: 'Elina',
		category: 'ForHome',
		price: 25000,
		countInStock: 5,
		rating: 4.9,
		numReviews: 8,
		discount: true,
	},
	{
		_id: nextId('product-'),
		name: 'Плед Arya Хлопок Sambra',
		images: [
			'/img/for_home/Rug_Akrila/1.webp',
			'/img/for_home/Rug_Akrila/2.webp',
			'/img/for_home/Rug_Akrila/3.webp',
			'/img/for_home/Rug_Akrila/4.webp',
			'/img/for_home/Rug_Akrila/5.webp',
		],
		colors: ['#D6B487', '#3B2B21', '#A18C5C', '#BDB382'],
		description: 'Плед Arya Хлопок 200X220 Sambra',
		brand: 'Arya',
		category: 'ForHome',
		price: 13000,
		countInStock: 5,
		rating: 4.7,
		numReviews: 8,
		discount: false,
	},
	{
		_id: nextId('product-'),
		name: 'Комплект покрывало DARLISHOP флоренция Евро',
		images: [
			'/img/for_home/Rug_DARLISHOP/1.webp',
			'/img/for_home/Rug_DARLISHOP/2.webp',
			'/img/for_home/Rug_DARLISHOP/3.webp',
			'/img/for_home/Rug_DARLISHOP/4.webp',
		],
		colors: ['#383130', '#D4C9C4', '#9E9388', '#BAB9B6'],
		description:
			'Комплект из однотонного покрывала и двух наволочек. Покрывало стеганное, выполнено в двустороннем дизайне. Приятное для тела, легкое и простое в уходе. Подходит для кровати больших размеров. Покрывало многослойное: центральный слой из синтепона добавляет красивый объем и дополнительную мягкость. Стильный комплект привнесет уют и гармонию в спальню.',
		brand: 'Darlishop',
		category: 'ForHome',
		price: 4900,
		countInStock: 40,
		rating: 4,
		numReviews: 13,
		discount: false,
	},
	{
		_id: nextId('product-'),
		name: 'Чемодан Brics BBG28314 Bellagio Travel Trunk M',
		images: [
			'/img/for_travel/BricsBBG28314/1.jpg',
			'/img/for_travel/BricsBBG28314/2.jpg',
			'/img/for_travel/BricsBBG28314/3.jpg',
			'/img/for_travel/BricsBBG28314/4.jpg',
			'/img/for_travel/BricsBBG28314/5.jpg',
			'/img/for_travel/BricsBBG28314/6.jpg',
			'/img/for_travel/BricsBBG28314/7.jpg',
		],
		colors: ['#152036', '#0F1312', '#322D29', '#DDD6C6'],
		description: 'Чемодан Brics BBG28314 Bellagio Travel Trunk M *902',
		brand: 'Brics',
		category: 'ForTravel',
		price: 69900,
		countInStock: 3,
		rating: 4.9,
		numReviews: 30,
		discount: false,
	},
	{
		_id: nextId('product-'),
		name: 'Чемодан Robinzon RP123-3 Santorini Deluxe S',
		images: [
			'/img/for_travel/RobinzonRP123-3/1.jpg',
			'/img/for_travel/RobinzonRP123-3/2.jpg',
			'/img/for_travel/RobinzonRP123-3/3.jpg',
			'/img/for_travel/RobinzonRP123-3/4.jpg',
			'/img/for_travel/RobinzonRP123-3/5.jpg',
			'/img/for_travel/RobinzonRP123-3/6.jpg',
		],
		colors: ['#546F90', '#2E3359', '#554B75', '#261F22'],
		description:
			'Чемодан Robinzon размера S изготовлен из высокопрочного полипропилена надежный и незаменимый аксессуар Вашей поездки. Такой чемодан станет надежным и незаменимым аксессуаром в Вашей поездке. Легкий и ударопрочный корпус весом всего 2,3 кг позволит вместить все, что так необходимо. Двойные бесшумные колеса с поворотом на 360 градусов обеспечат отличную проходимость чемодана и плавность его хода. Встроенный замок TSA выполнен в цвет чемодана и встроен в корпус, а значит, дополнительно защищён от внешних поломок в путешествии. USB-разъем позволит удобно зарядить гаджет, когда Вам нужно. (Power bank в комплекте не поставляется). Прочная телескопическая ручка из авиационного алюминия имеет 3 положения - подойдет для разного роста. Внутри чемодана два отделения с внутренними сетчатыми перегородками, на одной из них дополнительные два кармана. Один из которых из водонепроницаемого материала. Мы используем только первичный полипропилен, для того чтобы Ваш чемодан служил долго. Мы контролируем качество каждой детали, поэтому даем 5 лет гарантии на чемоданы линейки Santorini Deluxe.',
		brand: 'Robinzon',
		category: 'ForTravel',
		price: 19900,
		countInStock: 7,
		rating: 4.3,
		numReviews: 10,
		discount: true,
	},
	{
		_id: nextId('product-'),
		name: 'Чемодан Roncato 416212 Joy Medium Trolley Expandable 63',
		images: [
			'/img/for_travel/Roncato416212/1.jpg',
			'/img/for_travel/Roncato416212/2.jpg',
			'/img/for_travel/Roncato416212/3.jpg',
			'/img/for_travel/Roncato416212/4.jpg',
			'/img/for_travel/Roncato416212/5.jpg',
			'/img/for_travel/Roncato416212/6.jpg',
			'/img/for_travel/Roncato416212/7.jpg',
		],
		colors: ['#495FC2', '#8C2D2D', '#A8984A', '#A1A88C'],
		description:
			'Чемодан Roncato 416212 Joy Medium Trolley 63 входит в практичную и недорогую коллекцию от крупнейшего в Италии производителя багажа. Плотный, несминаемый и непромокаемый полиэстер, лаконичный и хорошо продуманный дизайн и функционал. Простые и логичные формы, узкая цветовая гамма и никаких лишних дорогих наворотов.',
		brand: 'Roncato',
		category: 'ForTravel',
		price: 23900,
		countInStock: 2,
		rating: 3.9,
		numReviews: 4,
		discount: true,
	},
	{
		_id: nextId('product-'),
		name: 'Очки в форме бабочка - Tropical by Safilo W DEL RIO',
		images: [
			'/img/glasses/Sunscreens_Butterfly/1.jpg',
			'/img/glasses/Sunscreens_Butterfly/2.jpg',
			'/img/glasses/Sunscreens_Butterfly/3.jpg',
			'/img/glasses/Sunscreens_Butterfly/4.jpg',
		],
		colors: ['#536166', '#BCBABC', '#87827A', '#7EA37A'],
		description:
			'Каждая модель Tropical отличается непревзойденным качеством и неповторимым дизайном. В линейке солнцезащитных очков умело сочетаются неизменная классика и современные тенденции, что позволяет подчеркнуть индивидуальность стиля ее обладателя.',
		brand: 'Tropical',
		category: 'Glasses',
		price: 3700,
		countInStock: 8,
		rating: 4.4,
		numReviews: 5,
		discount: false,
	},
	{
		_id: nextId('product-'),
		name: 'Chanel CH544 1674 3N',
		images: [
			'/img/glasses/Sunscreens_Channel/1.jpg',
			'/img/glasses/Sunscreens_Channel/2.jpg',
			'/img/glasses/Sunscreens_Channel/3.jpg',
			'/img/glasses/Sunscreens_Channel/4.jpg',
		],
		colors: ['#A1958C', '#796385', '#96BAB8', '#63633F'],
		description:
			'100%-ная защита от UVA/UVB-излучения (CE) - Линзы с УФ-фильтром категории 3 - С возможностью установки диоптрических линз.',
		brand: 'Chanel',
		category: 'Glasses',
		price: 33000,
		countInStock: 8,
		rating: 4.9,
		numReviews: 5,
		discount: false,
	},
	{
		_id: nextId('product-'),
		name: 'Солнцезащитные очки Chanel CH5445H 1674/S5 3N',
		images: [
			'/img/glasses/Sunscreens_Chappel/1.jpg',
			'/img/glasses/Sunscreens_Chappel/2.jpg',
			'/img/glasses/Sunscreens_Chappel/3.jpg',
			'/img/glasses/Sunscreens_Chappel/4.jpg',
		],
		colors: ['#465959', '#AFAAB1', '#7A746E', '#849675'],
		description:
			'100%-ная защита от UVA/UVB-излучения (CE) - Линзы с УФ-фильтром категории 3 - С возможностью установки диоптрических линз.',
		brand: 'Chanel',
		category: 'Glasses',
		price: 48900,
		countInStock: 2,
		rating: 4.7,
		numReviews: 4,
		discount: true,
	},
	{
		_id: nextId('product-'),
		name: 'COCCOLO MICROFLEECE',
		images: [
			'/img/pet_products/COCCOL_ MICROFLEECE/1.webp',
			'/img/pet_products/COCCOL_ MICROFLEECE/2.webp',
			'/img/pet_products/COCCOL_ MICROFLEECE/3.webp',
		],
		colors: ['#777672', '#211A1B', '#13161F', '#f5f5dc'],
		description:
			'Софа Coccolo Microfleece, изготовленная из теплого и мягкого микрофлиса, идеально подходит для отдыха кошек и маленьких собак. Мягкие бортики и съемная подушка обеспечат максимальный комфорт вашему любимцу, в то время как особая форма с низким порожком позволит легко устроиться в софе или наоборот, выйти наружу.',
		brand: 'Ferplast',
		category: 'PetProducts',
		price: 6900,
		countInStock: 2,
		rating: 4.7,
		numReviews: 4,
		discount: true,
	},
	{
		_id: nextId('product-'),
		name: 'GIOTTO LUXOR BEIGE P',
		images: [
			'/img/pet_products/GIOTTO_LUXOR/1.webp',
			'/img/pet_products/GIOTTO_LUXOR/2.webp',
			'/img/pet_products/GIOTTO_LUXOR/3.webp',
			'/img/pet_products/GIOTTO_LUXOR/4.webp',
		],
		colors: ['#f5f5dc', '#9E7D72', '#F0D5A8', '#76918B'],
		description:
			'Кожаные шлейки для собак Giotto равномерно распределяют тяговую силу и тем самым предотвращают повреждения шеи собаки. Шлейки линейки Giotto оснащены инновационной запатентованной системой микрорегулировки и прекрасно адаптируются под размер собаки.',
		brand: 'Ferplast',
		category: 'PetProducts',
		price: 15000,
		countInStock: 8,
		rating: 4.4,
		numReviews: 15,
		discount: false,
	},
	{
		_id: nextId('product-'),
		name: 'Поводок-рулетка для собак Flexi New Classic L ленточный черный 5 м',
		images: [
			'/img/pet_products/FLEXI_CLASSIC/1.jpg',
			'/img/pet_products/FLEXI_CLASSIC/2.jpg',
			'/img/pet_products/FLEXI_CLASSIC/3.jpg',
			'/img/pet_products/FLEXI_CLASSIC/3.jpg',
		],
		colors: ['#3A3A3B', '#273652', '#38321E', '#398742'],
		description:
			'Удобный ленточный поводок-рулетка предназначен для выгула собак весом до 50 кг. Лента поводка автоматически сматывается, и поводок в процессе использования не провисает, не касается грунта и таким образом не пачкается и не перетирается. Поводок не нужно подбирать руками, когда питомец подошел ближе, таким образом ваши руки всегда чистые.',
		brand: 'Flexi',
		category: 'PetProducts',
		price: 1900,
		countInStock: 17,
		rating: 4.2,
		numReviews: 4,
		discount: true,
	},
];

export default products;
